######################################################################
#                     --  configuration switch --                    #
######################################################################
######################################################################
#                          -- server --                              #
######################################################################
server:
  port: 8080

######################################################################
#                          -- eureka --                              #
######################################################################
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

######################################################################
#                           -- item --                               #
######################################################################
ll:
  name: lessons learned
  # 版本
  version: 1.0.0
  # 版权年份
  year: 2020
  # 成员
  member: ChenYongbin、MengXiaodong、ChenYongkun