######################################################################
#                     --  configuration switch --                    #
######################################################################
######################################################################
#                          -- server --                              #
######################################################################
server:
  port: 8080

######################################################################
#                          -- eureka --                              #
######################################################################
eureka:
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    # service-url.defaultZone && instance.hostname 解决 Connect to localhost:8761 timed out
    service-url:
      defaultZone:  http://ll-eureka:8080/eureka
  instance:
    # hostname 代替IP
    hostname: ll-eureka

######################################################################
#                           -- item --                               #
######################################################################
ll:
  name: lessons learned
  # 版本
  version: 1.0.0
  # 版权年份
  year: 2020
  # 成员
  member: ChenYongbin、MengXiaodong、ChenYongkun